# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.1-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hello@example.com
      PGADMIN_DEFAULT_PASSWORD: hello
    ports:
      - 8080:80