# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.1-bullseye
    restart: always
    environment:
      - POSTGRES_PASSWORD=J7vybovWx:3qstsj
    volumes:
      - ./docker/postgresql/initdb.d:/docker-entrypoint-initdb.d


  adminer:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hello@example.com
      PGADMIN_DEFAULT_PASSWORD: hello
    ports:
      - 8080:80